### PR TITLE
Test ubuntu 22 04

### PR DESCRIPTION
**Pull request by fsb4000**
not for merge.
I'm just testing if CI will work with Ubuntu 22.04 and clang 14.

### CODE REVIEW

**Comment by fsb4000** [comment]
```
lib/dhparams.c:18:5: error: ‘DH_set0_pqg’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
```
Oh, it can't be even built on Ubuntu 22.04
😿
